(deftemplate campeon
	(slot nombre (type SYMBOL))
	(slot primario (type SYMBOL))
	(slot secundario (type SYMBOL))
	(slot salud (type INTEGER))
	(slot ataque (type INTEGER))
	(slot hechizo (type INTEGER))
	(slot dificultad (type INTEGER))
	(slot fecha (type STRING))
	(slot puntosip (type INTEGER))
	(slot puntosrp (type INTEGER))
	(slot prioridad (type INTEGER) )
	(multislot good_against)
	(multislot bad_against)
	(multislot good_with)
)