(deftemplate campeon
	(slot nombre (type STRING))
	(slot primario (type STRING))
	(slot secundario (type STRING))
	(slot salud (type INTEGER))
	(slot ataque (type INTEGER))
	(slot hechizo (type INTEGER))
	(slot dificultad (type INTEGER))
	(slot fecha (type STRING))
	(slot puntosip (type INTEGER))
	(slot puntosrp (type INTEGER))
	(slot prioridad (type INTEGER))
	(multislot ga)
	(multislot ba)
	(multislot gw)
)